name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [ '1.21' ]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha

      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.32.0/tinygo_0.32.0_amd64.deb
          sudo dpkg -i tinygo_0.32.0_amd64.deb
          sudo apt-get install -f

      - name: Build WebAssembly
        run: |
          tinygo build -o main.wasm -target wasm ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifact_${{ steps.short-sha.outputs.short_sha }}
          path: main.wasm
